### All venues
GET http://localhost:3000/venues

### Fetch nonexisting venues
GET http://localhost:3000/venues/64172f654f7a525ca87aad3d
Accept: application/json

### Fetch existing venue by its name
GET http://localhost:3000/venues/name/SKC Kragujevac

### Fetch existing venues by their category
GET http://localhost:3000/venues/category/other

### Create new venue
POST http://localhost:3000/venues/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxlbmF0b2Rvc2lqZXZpYyIsInJvbGUiOiJhZG1pbiIsImlkIjoiNjQyODczZWZkZGVjMjNhMjBjYmZlMjE3IiwibmFtZSI6IkxlbmEgVG9kb3NpamV2acSHIiwiaWF0IjoxNjgxMDM0MTQ5fQ.2CrP9P047WAbFTYDlkCA-f3RFF_mHlhY1T0zlkInJVM

{
  "name": "CZNTK \"Abrašević\" Kragujevac",
  "description": "Centar za negovanje tradicionalne kulture „Abrašević“ Kragujevac, osnovan je 2006. godine, od strane grada Kragujevca i pravni je i umetnički sledbenik, KUD-a „Abrašević“, osnovanog daleke 1905. godine. Po svom konceptu rada, ovo je jedini Centar ove vrste u zemlji i predstavlja ustanovu kulture od nacionalnog interesa. Polaznici se osposobljavaju za više vidova umetnosti, ali i edukuju kako se na pravi način i kojim sredstvima čuva tradicija, kultura i umetnost. Centar danas ima oko 500 članova, razvrstanih u više sekcija, koje rade sa velikim uspehom. Osnovna delatnost Centra je izvođačka umetnost. Ovde se neguje tradicionalna kultura i umetnost kako Srba tako i ostalih naroda koji žive u Srbiji. Ansambli „Abraševića“ gostovali su u više od 30 zemalja sveta, i do sada izveli više hiljada umetničkih programa, predstava, scenskih prikaza, književnih programa i koncerata.„Abrašević“ je dobitnik najviših društvenih i umetničkih priznanja i nagrada.",
  "img": "https://abrasevickg.rs/wp-content/uploads/2020/09/bio_hed_DVA.jpg",
  "category": "other",
  "address": {
    "street": "Dr Jovana Ristića 15",
    "city": "Kragujevac",
    "zip": "34 000"
  },
  "info": {
    "email": "info@abrasevickg.rs",
    "web": "https://abrasevickg.rs/#",
    "telephone": "+381 34 501 330"
  }
}